server:
  port: 8866
spring:
  datasource:
    url: jdbc:mysql://192.168.18.230:3306/micromall?serverTimezone=UTC&useSSL=false&useUnicode=true&characterEncoding=UTF-8&allowPublicKeyRetrieval=true
    username: root
    password: 123456
    druid:
      initial-size: 5 #????????????
      min-idle: 10 #?????????????
      max-active: 20 #?????????
      web-stat-filter:
        exclusions: "*.js,*.gif,*.jpg,*.png,*.css,*.ico,/druid/*" #????????????????
      stat-view-servlet: #????????????????????????
        login-username: druid
        login-password: druid
  application:
    name: tulingmall-product
  cloud:
    nacos:
      discovery:
        server-addr: 192.168.18.230:8848

mybatis:
  mapper-locations:
    - classpath:dao/*.xml
    - classpath*:com/**/mapper/*.xml
management: #????SpringBoot Admin????
  endpoints:
    web:
      exposure:
        include: '*'
  endpoint:
    health:
      show-details: always
